name:                agda-signature-extractor
version:             0.1.0.0
github:              "githubuser/agda-signature-extractor"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/agda-signature-extractor#readme>

dependencies:
- base >= 4.7 && < 5
- Agda
- directory
- mtl
- filepath
- filemanip
- optparse-applicative
- aeson
- bytestring

language: GHC2021

default-extensions:
- BlockArguments
- DuplicateRecordFields
- LambdaCase
- OverloadedRecordDot
- OverloadedStrings
- NoFieldSelectors
- RecordWildCards

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  agda-signature-extractor:
    main:                Main.hs
    source-dirs:         app
